# Generated by Django 4.0 on 2022-01-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountmaster',
            name='balance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bankaccountmaster',
            name='initial_balance',
            field=models.FloatField(null=True),
        ),
    ]
