# Generated by Django 4.0 on 2022-01-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_bankaccountmaster_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountmaster',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
