# Generated by Django 4.0 on 2022-01-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_bankaccountmaster_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountmaster',
            name='credit_balance',
            field=models.FloatField(null=True),
        ),
    ]
