# Generated by Django 4.0 on 2022-01-10 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_tenant', '0013_employee_branches'),
        ('company', '0005_bankaccountmaster_credit_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.FloatField(null=True)),
                ('balance', models.FloatField(null=True)),
                ('cash_ac_name', models.FloatField(null=True)),
                ('credit_balance', models.FloatField(null=True)),
                ('branches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_tenant.branches')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_tenant.company')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.owner')),
            ],
            options={
                'db_table': 'cash_master',
            },
        ),
    ]
