# Generated by Django 4.0 on 2022-01-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_cashmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmaster',
            name='cash_ac_name',
            field=models.CharField(max_length=30),
        ),
    ]
