# Generated by Django 4.0 on 2022-01-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_cashmaster_cash_ac_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccountmaster',
            old_name='branch',
            new_name='cash_ac_name',
        ),
        migrations.AddField(
            model_name='bankaccountmaster',
            name='cash_credit_balance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bankaccountmaster',
            name='opening_balance',
            field=models.FloatField(null=True),
        ),
    ]
