# Generated by Django 4.0 on 2022-01-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_rename_branch_bankaccountmaster_cash_ac_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountmaster',
            name='cash_balance',
            field=models.FloatField(null=True),
        ),
    ]
