# Generated by Django 4.0 on 2022-01-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_bankaccountmaster_cash_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountmaster',
            name='cash_debit_balance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bankaccountmaster',
            name='debit_balance',
            field=models.FloatField(null=True),
        ),
    ]
