# Generated by Django 4.0 on 2022-01-11 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_tenant', '0013_employee_branches'),
        ('company', '0010_bankaccountmaster_cash_debit_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance_bank', models.FloatField(null=True)),
                ('closing_balance_bank', models.FloatField(null=True)),
                ('closing_balance_cash', models.FloatField(null=True)),
                ('cash_opening_balance', models.FloatField(null=True)),
                ('bank_balance', models.FloatField(null=True)),
                ('cash_balance', models.FloatField(null=True)),
                ('date', models.DateTimeField()),
                ('credit_balance_bank', models.FloatField(null=True)),
                ('debit_balance_bank', models.FloatField(null=True)),
                ('cash_credit_balance', models.FloatField(null=True)),
                ('cash_debit_balance', models.FloatField(null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('branches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_tenant.branches')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_tenant.company')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.owner')),
            ],
            options={
                'db_table': 'daily_session_master',
            },
        ),
    ]
