# Generated by Django 4.0 on 2021-12-30 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=30)),
                ('ar_name', models.CharField(max_length=30)),
                ('en_place', models.CharField(max_length=30)),
                ('ar_place', models.CharField(max_length=30)),
                ('en_district', models.CharField(max_length=30)),
                ('ar_district', models.CharField(max_length=30)),
                ('cr_no', models.CharField(max_length=15)),
                ('vat_no', models.CharField(max_length=15)),
                ('lan_no', models.CharField(max_length=15)),
                ('logo', models.ImageField(null=True, upload_to='media/')),
                ('status', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='shared_tenant.user')),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
