# Generated by Django 4.0 on 2021-12-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_tenant', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
    ]
