# Generated by Django 4.0 on 2021-12-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_tenant', '0006_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
