# Generated by Django 4.0 on 2022-01-05 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_tenant', '0008_alter_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=30)),
                ('ar_name', models.CharField(max_length=30)),
                ('en_place', models.CharField(max_length=30)),
                ('ar_place', models.CharField(max_length=30)),
                ('en_district', models.CharField(max_length=30)),
                ('ar_district', models.CharField(max_length=30)),
                ('cr_no', models.CharField(max_length=15)),
                ('vat_no', models.CharField(max_length=15)),
                ('lan_no', models.CharField(max_length=15)),
                ('logo', models.ImageField(null=True, upload_to='media/')),
                ('status', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_tenant.company')),
            ],
            options={
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='BranchManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('iqama_no', models.CharField(max_length=15, unique=True)),
                ('branches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches_id', to='shared_tenant.branches')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_tenant.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_tenant.user')),
            ],
            options={
                'db_table': 'branch_manager',
            },
        ),
    ]
