# Generated by Django 4.0 on 2022-01-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_tenant', '0009_branches_branchmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_branch_user',
            field=models.BooleanField(default=False),
        ),
    ]
