# Generated by Django 4.0 on 2022-01-05 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_tenant', '0010_user_is_branch_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmanager',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_manager_id', to='shared_tenant.user'),
        ),
    ]
