# Generated by Django 4.0 on 2022-01-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_tenant', '0011_alter_branchmanager_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='branch_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
